import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth-config';
import { generateParentInsights } from '@/lib/openai';

export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { 
      familyId,
      timeframe = '30days',
      includeGoals = true,
      includeRecommendations = true
    } = await request.json();

    if (!familyId) {
      return NextResponse.json({ error: 'Family ID is required' }, { status: 400 });
    }

    // Fetch family data for analysis
    const familyData = await fetchFamilyData(familyId, timeframe);
    
    if (!familyData) {
      return NextResponse.json({ error: 'Family data not found' }, { status: 404 });
    }

    // Generate parent insights using OpenAI
    const insights = await generateParentInsights({
      ...familyData,
      timeframe,
      includeGoals,
      includeRecommendations
    });

    // Save insights to database
    await saveInsights(familyId, insights, session.user.id);

    return NextResponse.json({
      success: true,
      insights,
      familyId,
      timeframe,
      generatedAt: new Date().toISOString()
    });

  } catch (error) {
    console.error('Error in parent insights:', error);
    return NextResponse.json(
      { error: 'Failed to generate parent insights' },
      { status: 500 }
    );
  }
}

async function fetchFamilyData(familyId: string, timeframe: string) {
  try {
    // Mock data - replace with actual database queries
    return {
      familyId,
      timeframe,
      children: [
        {
          id: 'child1',
          name: 'Child 1',
          age: 10,
          skillLevel: 'intermediate',
          recentPerformance: {
            drillsCompleted: 15,
            averageRating: 7.5,
            improvementTrend: 'positive',
            consistencyScore: 8.2
          },
          strengths: ['teamwork', 'effort', 'coachability'],
          challenges: ['shooting consistency', 'defensive positioning'],
          goals: ['improve shooting', 'make school team'],
          parentEngagement: {
            practiceSupport: 'high',
            gameAttendance: 'regular',
            homeTraining: 'active'
          }
        }
      ],
      familyEngagement: {
        practiceFrequency: 'daily',
        parentInvolvement: 'high',
        supportLevel: 'excellent',
        communicationStyle: 'collaborative'
      },
      overallProgress: {
        totalDrillsCompleted: 45,
        totalWorkoutsCompleted: 20,
        averageFamilyRating: 7.8,
        improvementTrend: 'positive',
        consistencyAcrossChildren: 'high'
      },
      challenges: [
        'Balancing multiple children\'s schedules',
        'Maintaining motivation during plateaus',
        'Managing competitive dynamics between siblings'
      ],
      successes: [
        'Consistent practice routine established',
        'All children showing improvement',
        'Strong family support system'
      ],
      parentPreferences: {
        communicationStyle: 'detailed',
        feedbackFrequency: 'weekly',
        involvementLevel: 'high',
        focusAreas: ['skill development', 'character building']
      }
    };
  } catch (error) {
    console.error('Error fetching family data:', error);
    return null;
  }
}

async function saveInsights(familyId: string, insights: any, userId: string) {
  try {
    // Mock implementation - replace with actual database save
    console.log('Saving insights for family:', familyId);
    console.log('Generated by user:', userId);
    console.log('Insights:', insights);
    return true;
  } catch (error) {
    console.error('Error saving insights:', error);
    return false;
  }
} 