"use strict";(()=>{var e={};e.id=76,e.ids=[76],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},27790:e=>{e.exports=require("assert")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},17702:e=>{e.exports=require("events")},32615:e=>{e.exports=require("http")},35240:e=>{e.exports=require("https")},86624:e=>{e.exports=require("querystring")},17360:e=>{e.exports=require("url")},21764:e=>{e.exports=require("util")},71568:e=>{e.exports=require("zlib")},93516:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>m,patchFetch:()=>g,requestAsyncStorage:()=>d,routeModule:()=>l,serverHooks:()=>x,staticGenerationAsyncStorage:()=>h});var a={};r.r(a),r.d(a,{POST:()=>c,dynamic:()=>u});var o=r(79182),n=r(72007),s=r(56719),i=r(93442),p=r(15649);let u="force-dynamic";async function c(e){try{let t=await (0,p.getServerSession)();if(!t?.user?.id)return i.NextResponse.json({error:"Unauthorized"},{status:401});let{message:r}=await e.json(),a=await fetch("https://apps.abacus.ai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${process.env.ABACUSAI_API_KEY}`},body:JSON.stringify({model:"gpt-4.1-mini",messages:[{role:"system",content:`You are Coach Alex, a friendly basketball coach for kids aged 6-13. You help young players with:
            - Basketball fundamentals and techniques
            - Motivation and encouragement
            - Practice tips and drills
            - Building confidence and skills
            - Answering questions about basketball
            
            Keep responses:
            - Age-appropriate and encouraging
            - Under 150 words
            - Focused on basketball and skill development
            - Positive and supportive
            - Include practical tips when relevant
            
            Always be enthusiastic and use emojis occasionally to keep it fun!`},{role:"user",content:r}],max_tokens:200,temperature:.7,stream:!0})});if(!a.ok)throw Error("Failed to get AI response");let o=new TextEncoder,n=new ReadableStream({async start(e){try{let t=a.body?.getReader();if(!t){e.error("No response body");return}let r=new TextDecoder,n="";for(;;){let{done:a,value:s}=await t.read();if(a)break;let i=(n+=r.decode(s,{stream:!0})).split("\n");for(let t of(n=i.pop()||"",i))if(t.startsWith("data: ")){let r=t.slice(6);if("[DONE]"===r){e.enqueue(o.encode("data: [DONE]\n\n")),e.close();return}try{let t=JSON.parse(r),a=t.choices[0]?.delta?.content||"";a&&e.enqueue(o.encode(`data: ${JSON.stringify({content:a})}

`))}catch(e){}}}e.enqueue(o.encode("data: [DONE]\n\n")),e.close()}catch(t){console.error("Streaming error:",t),e.error(t)}}});return new Response(n,{headers:{"Content-Type":"text/plain; charset=utf-8","Cache-Control":"no-cache"}})}catch(e){return console.error("Error in AI chat:",e),i.NextResponse.json({error:"Failed to get AI response"},{status:500})}}let l=new o.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/api/ai/chat/route",pathname:"/api/ai/chat",filename:"route",bundlePath:"app/api/ai/chat/route"},resolvedPagePath:"/home/ubuntu/hoopsquest/app/app/api/ai/chat/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:d,staticGenerationAsyncStorage:h,serverHooks:x}=l,m="/api/ai/chat/route";function g(){return(0,s.patchFetch)({serverHooks:x,staticGenerationAsyncStorage:h})}}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[372,649,609],()=>r(93516));module.exports=a})();