-- CreateTable
CREATE TABLE "ReportCard" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "assessorId" TEXT NOT NULL,
    "assessmentDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ballHandling" INTEGER NOT NULL DEFAULT 1,
    "shooting" INTEGER NOT NULL DEFAULT 1,
    "passing" INTEGER NOT NULL DEFAULT 1,
    "defense" INTEGER NOT NULL DEFAULT 1,
    "rebounding" INTEGER NOT NULL DEFAULT 1,
    "footwork" INTEGER NOT NULL DEFAULT 1,
    "conditioning" INTEGER NOT NULL DEFAULT 1,
    "teamwork" INTEGER NOT NULL DEFAULT 1,
    "leadership" INTEGER NOT NULL DEFAULT 1,
    "basketballIQ" INTEGER NOT NULL DEFAULT 1,
    "effort" INTEGER NOT NULL DEFAULT 1,
    "attitude" INTEGER NOT NULL DEFAULT 1,
    "coachability" INTEGER NOT NULL DEFAULT 1,
    "consistency" INTEGER NOT NULL DEFAULT 1,
    "improvement" INTEGER NOT NULL DEFAULT 1,
    "strengths" TEXT,
    "areasForImprovement" TEXT,
    "specificGoals" TEXT,
    "parentNotes" TEXT,
    "overallRating" INTEGER NOT NULL DEFAULT 1,
    "recommendedFocus" TEXT,
    "nextLevelReadiness" INTEGER NOT NULL DEFAULT 1,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ReportCard_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ReportCard_assessorId_fkey" FOREIGN KEY ("assessorId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
